### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tohd** [HiruNya/HentaiBot#8]
$ python3 HentaiBot.py
`Success! To Channel: ****************,    Sent 10 r/nsfw Posts
Traceback (most recent call last):
  File "HentaiBot.py", line 217, in <module>
    start()
  File "HentaiBot.py", line 185, in start
    r_num = subred["posts"]
TypeError: 'NoneType' object is not subscriptable
`
It posts the pictures, but errors out. What do?

**Comment by tohd** [comment]
nvm its just that im only using the reddit part
